"""Strategy engine data model — the "brain" that steers the whole value chain.

A :class:`Strategy` captures the big-picture, north-star goal ("control the
Brazil->Nigeria raw-sugar chain, 50k MT/quarter at >$18/MT margin") and breaks
it into objectives across the four pillars of a trade business:

    origination -> demand (buy-side/off-take) -> supply (sell-side origin) ->
    execution (negotiate + close)

The cadence layer turns that standing strategy into concrete week-by-week and
day-to-day work via :class:`StrategyTask` rows, which the strategy service
generates from the live state of the user's opportunities.
"""
from datetime import date, datetime

from sqlalchemy import (
    JSON,
    Boolean,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin

STRATEGY_STATUSES = ["active", "paused", "achieved", "archived"]

# The four pillars of controlling the value chain.
PILLARS = ["origination", "demand", "supply", "execution"]
PILLAR_LABELS = {
    "origination": "Origination",
    "demand": "Demand (Buy-side)",
    "supply": "Supply (Sell-side)",
    "execution": "Execution & Close",
}

TASK_STATUSES = ["todo", "doing", "done", "skipped"]
TASK_CADENCES = ["daily", "weekly", "once"]
TASK_PRIORITIES = ["high", "medium", "low"]

# Where a row sits in the decomposition tree. A strategic objective becomes an
# ``outcome``, which is broken into ``milestone``s, then ``task``s and ``subtask``s.
# Pre-existing rows are plain ``task``s, which keeps old data valid.
TASK_KINDS = ["outcome", "milestone", "task", "subtask"]

# Who is expected to move the task forward.
TASK_ASSIGNEES = ["agent", "human"]


class Strategy(Base, TimestampMixin):
    __tablename__ = "strategies"

    id: Mapped[int] = mapped_column(primary_key=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)

    # The big-picture goal, in the user's own words.
    north_star: Mapped[str | None] = mapped_column(Text)

    commodity: Mapped[str | None] = mapped_column(String(128), index=True)
    origin_region: Mapped[str | None] = mapped_column(String(128))
    destination_region: Mapped[str | None] = mapped_column(String(128))

    # Quantified targets over the horizon.
    horizon: Mapped[str] = mapped_column(String(32), default="quarter", nullable=False)
    target_volume_mt: Mapped[float | None] = mapped_column(Float)
    target_margin_per_mt: Mapped[float | None] = mapped_column(Float)

    # Objectives per pillar: {"origination": {"objective": str, "kpi": str,
    # "target": number, "cadence_target": {...}}, ...}. Free-form JSON so the
    # AI planner can enrich it without migrations.
    pillars: Mapped[dict] = mapped_column(JSON, default=dict, nullable=False)

    status: Mapped[str] = mapped_column(
        String(32), default="active", index=True, nullable=False
    )
    owner_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL")
    )


class StrategyTask(Base, TimestampMixin):
    """A concrete action generated by (or added to) a strategy's cadence."""

    __tablename__ = "strategy_tasks"

    id: Mapped[int] = mapped_column(primary_key=True)
    strategy_id: Mapped[int] = mapped_column(
        ForeignKey("strategies.id", ondelete="CASCADE"), index=True, nullable=False
    )

    pillar: Mapped[str] = mapped_column(String(32), index=True, nullable=False)
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    detail: Mapped[str | None] = mapped_column(Text)

    cadence: Mapped[str] = mapped_column(String(16), default="weekly", nullable=False)
    priority: Mapped[str] = mapped_column(String(16), default="medium", nullable=False)
    status: Mapped[str] = mapped_column(
        String(16), default="todo", index=True, nullable=False
    )

    # The plan-week this task belongs to (Monday's date), so we can regenerate a
    # week's cadence without clobbering other weeks or manually-added tasks.
    week_start: Mapped[date | None] = mapped_column(Date, index=True)
    due_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # Optional link to the opportunity / lead this action concerns.
    opportunity_id: Mapped[int | None] = mapped_column(
        ForeignKey("opportunities.id", ondelete="SET NULL")
    )
    supplier_lead_id: Mapped[int | None] = mapped_column(
        ForeignKey("supplier_leads.id", ondelete="SET NULL")
    )
    buyer_lead_id: Mapped[int | None] = mapped_column(
        ForeignKey("buyer_leads.id", ondelete="SET NULL")
    )

    # "auto" when generated by the cadence engine, "manual" when user-added.
    source: Mapped[str] = mapped_column(String(16), default="auto", nullable=False)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # --- Decomposition tree ------------------------------------------------

    parent_id: Mapped[int | None] = mapped_column(
        ForeignKey("strategy_tasks.id", ondelete="CASCADE"), index=True
    )
    kind: Mapped[str] = mapped_column(
        String(16), default="task", index=True, nullable=False
    )
    #: Sort order among siblings, so a decomposed plan keeps its sequence.
    position: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    #: Ids of sibling tasks that must complete first. Stored as JSON rather than a
    #: join table because dependencies are few, always read with the task, and never
    #: queried in reverse.
    depends_on_ids: Mapped[list] = mapped_column(JSON, default=list, nullable=False)

    # --- Evidence-based completion -----------------------------------------

    #: What "done" actually means for this task, in plain language.
    acceptance_criteria: Mapped[str | None] = mapped_column(Text)

    #: When true, the task cannot be completed without at least one Evidence row.
    #: Set for tasks whose completion asserts a real-world commercial outcome.
    requires_evidence: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False
    )

    #: Populated when a human deliberately completes a task that lacked evidence.
    #: Recording the override keeps the audit trail honest instead of silently
    #: letting the requirement lapse.
    override_reason: Mapped[str | None] = mapped_column(Text)
    verified_by_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL")
    )
    verified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # --- Agent execution ---------------------------------------------------

    assignee: Mapped[str] = mapped_column(
        String(16), default="human", nullable=False
    )
    #: Which agent owns this task, when ``assignee == "agent"``.
    agent_key: Mapped[str | None] = mapped_column(String(64))
    #: Agent's self-reported confidence in its plan for this task (0-1).
    confidence: Mapped[float | None] = mapped_column(Float)
    #: The capability the executor should invoke. Persisted rather than re-derived
    #: from the title, so execution acts on what was planned, not on a guess.
    capability: Mapped[str | None] = mapped_column(String(32))
    #: Why the task cannot currently proceed, shown directly in the UI.
    blocked_reason: Mapped[str | None] = mapped_column(Text)
