"""Strategy engine data model — the "brain" that steers the whole value chain.

A :class:`Strategy` captures the big-picture, north-star goal ("control the
Brazil->Nigeria raw-sugar chain, 50k MT/quarter at >$18/MT margin") and breaks
it into objectives across the four pillars of a trade business:

    origination -> demand (buy-side/off-take) -> supply (sell-side origin) ->
    execution (negotiate + close)

The cadence layer turns that standing strategy into concrete week-by-week and
day-to-day work via :class:`StrategyTask` rows, which the strategy service
generates from the live state of the user's opportunities.
"""
from datetime import date, datetime

from sqlalchemy import JSON, Date, DateTime, Float, ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin

STRATEGY_STATUSES = ["active", "paused", "achieved", "archived"]

# The four pillars of controlling the value chain.
PILLARS = ["origination", "demand", "supply", "execution"]
PILLAR_LABELS = {
    "origination": "Origination",
    "demand": "Demand (Buy-side)",
    "supply": "Supply (Sell-side)",
    "execution": "Execution & Close",
}

TASK_STATUSES = ["todo", "doing", "done", "skipped"]
TASK_CADENCES = ["daily", "weekly", "once"]
TASK_PRIORITIES = ["high", "medium", "low"]


class Strategy(Base, TimestampMixin):
    __tablename__ = "strategies"

    id: Mapped[int] = mapped_column(primary_key=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)

    # The big-picture goal, in the user's own words.
    north_star: Mapped[str | None] = mapped_column(Text)

    commodity: Mapped[str | None] = mapped_column(String(128), index=True)
    origin_region: Mapped[str | None] = mapped_column(String(128))
    destination_region: Mapped[str | None] = mapped_column(String(128))

    # Quantified targets over the horizon.
    horizon: Mapped[str] = mapped_column(String(32), default="quarter", nullable=False)
    target_volume_mt: Mapped[float | None] = mapped_column(Float)
    target_margin_per_mt: Mapped[float | None] = mapped_column(Float)

    # Objectives per pillar: {"origination": {"objective": str, "kpi": str,
    # "target": number, "cadence_target": {...}}, ...}. Free-form JSON so the
    # AI planner can enrich it without migrations.
    pillars: Mapped[dict] = mapped_column(JSON, default=dict, nullable=False)

    status: Mapped[str] = mapped_column(
        String(32), default="active", index=True, nullable=False
    )
    owner_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL")
    )


class StrategyTask(Base, TimestampMixin):
    """A concrete action generated by (or added to) a strategy's cadence."""

    __tablename__ = "strategy_tasks"

    id: Mapped[int] = mapped_column(primary_key=True)
    strategy_id: Mapped[int] = mapped_column(
        ForeignKey("strategies.id", ondelete="CASCADE"), index=True, nullable=False
    )

    pillar: Mapped[str] = mapped_column(String(32), index=True, nullable=False)
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    detail: Mapped[str | None] = mapped_column(Text)

    cadence: Mapped[str] = mapped_column(String(16), default="weekly", nullable=False)
    priority: Mapped[str] = mapped_column(String(16), default="medium", nullable=False)
    status: Mapped[str] = mapped_column(
        String(16), default="todo", index=True, nullable=False
    )

    # The plan-week this task belongs to (Monday's date), so we can regenerate a
    # week's cadence without clobbering other weeks or manually-added tasks.
    week_start: Mapped[date | None] = mapped_column(Date, index=True)
    due_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # Optional link to the opportunity / lead this action concerns.
    opportunity_id: Mapped[int | None] = mapped_column(
        ForeignKey("opportunities.id", ondelete="SET NULL")
    )
    supplier_lead_id: Mapped[int | None] = mapped_column(
        ForeignKey("supplier_leads.id", ondelete="SET NULL")
    )
    buyer_lead_id: Mapped[int | None] = mapped_column(
        ForeignKey("buyer_leads.id", ondelete="SET NULL")
    )

    # "auto" when generated by the cadence engine, "manual" when user-added.
    source: Mapped[str] = mapped_column(String(16), default="auto", nullable=False)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
