"""Baseline schema — everything that existed before the execution spine.

Alembic was configured on this project but never used; ``create_all`` was the live
path. This revision captures the schema as it stood at that point so existing
databases can be stamped here without recreating anything, and fresh databases can
be built from migrations alone.
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('commodity', sa.String(length=128), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('credibility_score', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('red_flags', sa.JSON(), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_commodity'), 'suppliers', ['commodity'], unique=False)
    op.create_index(op.f('ix_suppliers_country'), 'suppliers', ['country'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('commodity', sa.String(length=128), nullable=False),
    sa.Column('volume_mt', sa.Float(), nullable=False),
    sa.Column('destination_country', sa.String(length=128), nullable=True),
    sa.Column('destination_port', sa.String(length=128), nullable=True),
    sa.Column('incoterms', sa.String(length=16), nullable=True),
    sa.Column('target_price_min', sa.Float(), nullable=True),
    sa.Column('target_price_max', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_commodity'), 'opportunities', ['commodity'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('north_star', sa.Text(), nullable=True),
    sa.Column('commodity', sa.String(length=128), nullable=True),
    sa.Column('origin_region', sa.String(length=128), nullable=True),
    sa.Column('destination_region', sa.String(length=128), nullable=True),
    sa.Column('horizon', sa.String(length=32), nullable=False),
    sa.Column('target_volume_mt', sa.Float(), nullable=True),
    sa.Column('target_margin_per_mt', sa.Float(), nullable=True),
    sa.Column('pillars', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_commodity'), 'strategies', ['commodity'], unique=False)
    op.create_index(op.f('ix_strategies_status'), 'strategies', ['status'], unique=False)
    op.create_table('buyer_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('buyer_name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('target_price_mt', sa.Float(), nullable=True),
    sa.Column('volume_mt', sa.Float(), nullable=True),
    sa.Column('appetite', sa.String(length=16), nullable=False),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('negotiation_stage', sa.Integer(), nullable=False),
    sa.Column('intel', sa.JSON(), nullable=False),
    sa.Column('disclosed', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_leads_opportunity_id'), 'buyer_leads', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_buyer_leads_status'), 'buyer_leads', ['status'], unique=False)
    op.create_table('supplier_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_title', sa.String(length=255), nullable=True),
    sa.Column('price_mt', sa.Float(), nullable=True),
    sa.Column('quoted_incoterms', sa.String(length=16), nullable=True),
    sa.Column('min_order_mt', sa.Float(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('payment_terms', sa.String(length=128), nullable=True),
    sa.Column('credibility_score', sa.Integer(), nullable=False),
    sa.Column('responsiveness_score', sa.Integer(), nullable=False),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('negotiation_stage', sa.Integer(), nullable=False),
    sa.Column('intel', sa.JSON(), nullable=False),
    sa.Column('disclosed', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_leads_opportunity_id'), 'supplier_leads', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_supplier_leads_status'), 'supplier_leads', ['status'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('commodity', sa.String(length=128), nullable=False),
    sa.Column('volume_mt', sa.Float(), nullable=False),
    sa.Column('buy_price', sa.Float(), nullable=False),
    sa.Column('sell_price', sa.Float(), nullable=False),
    sa.Column('freight_estimate', sa.Float(), nullable=False),
    sa.Column('incoterms', sa.String(length=16), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('structure', sa.String(length=32), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('supplier_lead_id', sa.Integer(), nullable=True),
    sa.Column('buyer_lead_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('margin_per_mt', sa.Float(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('total_margin', sa.Float(), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['buyer_lead_id'], ['buyer_leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_lead_id'], ['supplier_leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_commodity'), 'deals', ['commodity'], unique=False)
    op.create_index(op.f('ix_deals_opportunity_id'), 'deals', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_deals_stage'), 'deals', ['stage'], unique=False)
    op.create_table('strategy_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('pillar', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('cadence', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('supplier_lead_id', sa.Integer(), nullable=True),
    sa.Column('buyer_lead_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_lead_id'], ['buyer_leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_lead_id'], ['supplier_leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_tasks_pillar'), 'strategy_tasks', ['pillar'], unique=False)
    op.create_index(op.f('ix_strategy_tasks_status'), 'strategy_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_strategy_tasks_strategy_id'), 'strategy_tasks', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_strategy_tasks_week_start'), 'strategy_tasks', ['week_start'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_type'), 'documents', ['type'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('supplier_lead_id', sa.Integer(), nullable=True),
    sa.Column('buyer_lead_id', sa.Integer(), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('to_email', sa.String(length=255), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('message_id', sa.String(length=512), nullable=True),
    sa.Column('in_reply_to', sa.String(length=512), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('matched_side', sa.String(length=16), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('stage_at_send', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_lead_id'], ['buyer_leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_lead_id'], ['supplier_leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_messages_buyer_lead_id'), 'email_messages', ['buyer_lead_id'], unique=False)
    op.create_index(op.f('ix_email_messages_direction'), 'email_messages', ['direction'], unique=False)
    op.create_index(op.f('ix_email_messages_message_id'), 'email_messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_email_messages_opportunity_id'), 'email_messages', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_email_messages_status'), 'email_messages', ['status'], unique=False)
    op.create_index(op.f('ix_email_messages_supplier_lead_id'), 'email_messages', ['supplier_lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_messages_supplier_lead_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_status'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_opportunity_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_message_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_direction'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_buyer_lead_id'), table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_documents_type'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('activities')
    op.drop_index(op.f('ix_strategy_tasks_week_start'), table_name='strategy_tasks')
    op.drop_index(op.f('ix_strategy_tasks_strategy_id'), table_name='strategy_tasks')
    op.drop_index(op.f('ix_strategy_tasks_status'), table_name='strategy_tasks')
    op.drop_index(op.f('ix_strategy_tasks_pillar'), table_name='strategy_tasks')
    op.drop_table('strategy_tasks')
    op.drop_index(op.f('ix_deals_stage'), table_name='deals')
    op.drop_index(op.f('ix_deals_opportunity_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_commodity'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_supplier_leads_status'), table_name='supplier_leads')
    op.drop_index(op.f('ix_supplier_leads_opportunity_id'), table_name='supplier_leads')
    op.drop_table('supplier_leads')
    op.drop_index(op.f('ix_buyer_leads_status'), table_name='buyer_leads')
    op.drop_index(op.f('ix_buyer_leads_opportunity_id'), table_name='buyer_leads')
    op.drop_table('buyer_leads')
    op.drop_index(op.f('ix_strategies_status'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_commodity'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_commodity'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_country'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_commodity'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
