"""execution spine

Revision ID: d1b4c0734cba
Revises: 0001_baseline
Create Date: 2026-07-29 12:21:14.335453

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002_execution_spine"
down_revision: str | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('pillar', sa.String(length=32), nullable=True),
    sa.Column('agent_key', sa.String(length=64), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_key'), 'agent_runs', ['agent_key'], unique=False)
    op.create_index(op.f('ix_agent_runs_pillar'), 'agent_runs', ['pillar'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_strategy_id'), 'agent_runs', ['strategy_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=False),
    sa.Column('after', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_strategy_id'), 'audit_logs', ['strategy_id'], unique=False)
    op.create_table('kpi_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('pillar', sa.String(length=32), nullable=False),
    sa.Column('kpi_key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('source_task_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_task_id'], ['strategy_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_snapshots_pillar'), 'kpi_snapshots', ['pillar'], unique=False)
    op.create_index(op.f('ix_kpi_snapshots_strategy_id'), 'kpi_snapshots', ['strategy_id'], unique=False)
    op.create_table('agent_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=48), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['strategy_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_agent_actions_idempotency')
    )
    op.create_index(op.f('ix_agent_actions_action_type'), 'agent_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_agent_actions_run_id'), 'agent_actions', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_actions_state'), 'agent_actions', ['state'], unique=False)
    op.create_index(op.f('ix_agent_actions_strategy_id'), 'agent_actions', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_agent_actions_task_id'), 'agent_actions', ['task_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('email_message_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_by_type', sa.String(length=16), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['strategy_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_kind'), 'evidence', ['kind'], unique=False)
    op.create_index(op.f('ix_evidence_task_id'), 'evidence', ['task_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('request_summary', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['agent_actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_id', name='uq_approvals_action')
    )
    op.create_index(op.f('ix_approvals_action_id'), 'approvals', ['action_id'], unique=False)
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    op.create_index(op.f('ix_approvals_strategy_id'), 'approvals', ['strategy_id'], unique=False)
    # NOT NULL columns carry a ``server_default`` so the ALTER succeeds against a
    # table that already holds rows. Autogenerate omits these, which would make the
    # upgrade fail on every existing installation while passing on an empty dev DB.
    # The chosen defaults reproduce pre-execution-spine behaviour exactly: existing
    # tasks become ungated, human-owned, root-level ``task`` rows.
    # batch_alter_table rather than plain add_column: SQLite cannot ADD CONSTRAINT, so
    # the two foreign keys below would otherwise be silently absent there and the
    # schema would drift from the models. Batch mode recreates the table (copying
    # rows) on SQLite and emits ordinary ALTERs everywhere else.
    with op.batch_alter_table('strategy_tasks') as batch:
        batch.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch.add_column(sa.Column('kind', sa.String(length=16), nullable=False, server_default='task'))
        batch.add_column(sa.Column('position', sa.Integer(), nullable=False, server_default='0'))
        batch.add_column(sa.Column('depends_on_ids', sa.JSON(), nullable=False, server_default='[]'))
        batch.add_column(sa.Column('acceptance_criteria', sa.Text(), nullable=True))
        batch.add_column(sa.Column('requires_evidence', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch.add_column(sa.Column('override_reason', sa.Text(), nullable=True))
        batch.add_column(sa.Column('verified_by_id', sa.Integer(), nullable=True))
        batch.add_column(sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
        batch.add_column(sa.Column('assignee', sa.String(length=16), nullable=False, server_default='human'))
        batch.add_column(sa.Column('agent_key', sa.String(length=64), nullable=True))
        batch.add_column(sa.Column('confidence', sa.Float(), nullable=True))
        batch.add_column(sa.Column('blocked_reason', sa.Text(), nullable=True))
        batch.create_index(op.f('ix_strategy_tasks_kind'), ['kind'], unique=False)
        batch.create_index(op.f('ix_strategy_tasks_parent_id'), ['parent_id'], unique=False)
        batch.create_foreign_key(
            'fk_strategy_tasks_verified_by', 'users',
            ['verified_by_id'], ['id'], ondelete='SET NULL',
        )
        batch.create_foreign_key(
            'fk_strategy_tasks_parent', 'strategy_tasks',
            ['parent_id'], ['id'], ondelete='CASCADE',
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_tasks') as batch:
        batch.drop_constraint('fk_strategy_tasks_parent', type_='foreignkey')
        batch.drop_constraint('fk_strategy_tasks_verified_by', type_='foreignkey')
        batch.drop_index(op.f('ix_strategy_tasks_parent_id'))
        batch.drop_index(op.f('ix_strategy_tasks_kind'))
        for column in (
            'blocked_reason', 'confidence', 'agent_key', 'assignee', 'verified_at',
            'verified_by_id', 'override_reason', 'requires_evidence',
            'acceptance_criteria', 'depends_on_ids', 'position', 'kind', 'parent_id',
        ):
            batch.drop_column(column)
    op.drop_index(op.f('ix_approvals_strategy_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_status'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_action_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_evidence_task_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_kind'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_agent_actions_task_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_strategy_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_state'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_run_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_action_type'), table_name='agent_actions')
    op.drop_table('agent_actions')
    op.drop_index(op.f('ix_kpi_snapshots_strategy_id'), table_name='kpi_snapshots')
    op.drop_index(op.f('ix_kpi_snapshots_pillar'), table_name='kpi_snapshots')
    op.drop_table('kpi_snapshots')
    op.drop_index(op.f('ix_audit_logs_strategy_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_runs_strategy_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_pillar'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_key'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
