"""pre authorization grants

Revision ID: 4c302d8215d2
Revises: 0002_execution_spine
Create Date: 2026-07-29 12:26:54.139232

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003_pre_auth_grants"
down_revision: str | None = "0002_execution_spine"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_authorization_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=48), nullable=False),
    sa.Column('thread_key', sa.String(length=255), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('template_key', sa.String(length=64), nullable=False),
    sa.Column('approved_body_hash', sa.String(length=64), nullable=True),
    sa.Column('max_messages', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pre_authorization_grants_action_type'), 'pre_authorization_grants', ['action_type'], unique=False)
    op.create_index(op.f('ix_pre_authorization_grants_strategy_id'), 'pre_authorization_grants', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_pre_authorization_grants_thread_key'), 'pre_authorization_grants', ['thread_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pre_authorization_grants_thread_key'), table_name='pre_authorization_grants')
    op.drop_index(op.f('ix_pre_authorization_grants_strategy_id'), table_name='pre_authorization_grants')
    op.drop_index(op.f('ix_pre_authorization_grants_action_type'), table_name='pre_authorization_grants')
    op.drop_table('pre_authorization_grants')
    # ### end Alembic commands ###
